colorScheme = "noir"
defaultAppearance = "dark"
googleAnalytics = "G-KRR5D87FJC"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
replyByEmail = false
mainSections = [ "new" , "post", "test" ]
disableImageOptimization = false
disableTextInHeader = false
highlightCurrentMenuArea = true
smartTOC = true
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "page"
homepageImage = "img/cat_minimal.jpg"
showRecent = true 
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "/new/"
cardView = false 
cardViewScreenWidth = false
layoutBackgroundBlur = false

[article]
showDate = true
showViews = true
showLikes = true
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showComments = true
showHero = true
heroStyle = "basic"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = false
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showZenMode = true 

[list]
showHero = true
heroStyle = "big"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]

[taxonomy]
showTermCount = true
showHero = false
heroStyle = "big"
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = true
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]
apiKey = "AIzaSyCuCoT0_6Jbgb2852pYIRRl93AxyHaK3zY"
authDomain = "hugo-1a5e3.firebaseapp.com"
projectId = "hugo-1a5e3"
storageBucket = "hugo-1a5e3.appspot.com"
messagingSenderId = "239918323176"
appId = "1:239918323176:web:330e0e5b0196b4aef5005d"
measurementId = "G-CRNVW9JVMF"

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]
